insurance/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('insurance_app/', include('insurance_app.urls')),
    # url('django-webix/', include('django_webix.urls')),
]

insurance_app/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .forms import MyPasswordResetForm, MyPasswordChangeForm, MyAuthenticationForm
app_name='insurance_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('admin_page', views.admin_page, name='admin_page'),
    path('admin_page_contract', views.admin_page_contract, name='admin_page_contract'),
    path('login_user', auth_views.LoginView.as_view(template_name ='insurance_app/login_user.html', form_class = MyAuthenticationForm), name='login_user'),
    path('choose_company',views.choose_company, name='choose_company'),
    path('password/reset/', auth_views.PasswordResetView.as_view(template_name ='insurance_app/password_reset_form.html', form_class = MyPasswordResetForm,
    email_template_name = 'insurance_app/password_reset_email.html', success_url = reverse_lazy('insurance_app:password_reset_done')), name='password_reset'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name ='insurance_app/password_reset_done.html'), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(form_class = MyPasswordChangeForm, success_url = reverse_lazy('insurance_app:password_reset_complete'),template_name ='insurance_app/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password/reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name ='insurance_app/password_reset_complete.html'),
        name='password_reset_complete'),
    path('password/change/', auth_views.PasswordChangeView.as_view(template_name ='insurance_app/password_change_form.html',
                                                                   form_class = MyPasswordChangeForm,success_url = reverse_lazy('insurance_app:password_change_done') ), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(template_name ='insurance_app/password_change_done.html'), name='password_change_done'),
    path('add_userprofile',views.add_userprofile,name='add_userprofile'),
    path('logout', views.logout, name='logout'),
    path('register',views.register,name='register'),
    path('add_company', views.add_company, name='add_company'),
    path('accept_chosen_request/',views.accept_chosen_request, name='accept_chosen_request'),
    path('accept_all_request/',views.accept_all_request, name='accept_all_request'),
    path('load_to_database/',views.load_to_database, name='load_to_database'),
    path('add_chosen_company/',views.add_chosen_company,name='add_chosen_company'),
    path('delete_chosen_company/',views.delete_chosen_company,name='delete_chosen_company'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('update_database/',views.update_database, name='update_database'),
    path('auto_insurance', views.auto_insurance, name='auto_insurance'),
    path('auto_fill/',views.auto_fill, name='auto_fill'),
    path('company_list',views.company_list, name='company_list'),
    path('company_detail/<str:company_IM_NUMIDENT>',views.company_detail, name='company_detail'),
    path('add_info_to_company/<str:company_IM_NUMIDENT>',views.add_info_to_company, name='add_info_to_company'),
    path('order/<int:order_id>',views.order, name='order'),
    path('order_history',views.order_history, name='order_history'),
    path('reject_order/<int:order_id>',views.reject_order, name='reject_order'),
    path('order_offered',views.order_offered, name='order_offered'),
    path('company_is_chosen/<str:IM_NUMIDENT>',views.company_is_chosen, name='company_is_chosen'),
    path('create_contract/<str:IM_NUMIDENT>',views.create_contract, name='create_contract'),
    path('show_count_result/<int:order_id>',views.show_count_result, name='show_count_result'),
    path('show_count_error/<int:order_id>/<str:reason>',views.show_count_error, name='show_count_error'),
    path('show_order/<int:order_id>',views.show_order, name='show_order'),
    path('documents/<str:IM_NUMIDENT>',views.documents, name='documents'),
    path('received_contract_act/<int:doc_id>', views.received_contract_act, name='received_contract_act'),
    path('received_bill/<int:doc_id>', views.received_bill, name='received_bill'),
    path('try', views.tryx, name='try'),
    path('user_page', views.user_page, name='user_page'),
    path('company_logout/<str:IM_NUMIDENT>', views.company_logout, name='company_logout'),
]

insurance_app/views.py
import os
import pandas
from .classes import *
from django.contrib import auth
from .forms import *
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
import threading
from .processor import Processor
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q

def index(request):
    # companu = CompanyInfo.objects.get(IM_NUMIDENT=20693867)
    # tmp=Order(user=request.user, company_info=companu, reporting_date='2020-06-21', calc_type='1', offered=True)
    # tmp.save()
    companies = Company.objects.all()
    template = loader.get_template('insurance_app/index.html')
    context = {
        'companies': companies,
    }
    company_code = "19209435"
    api_key = "VChFavBht5ug"
    return HttpResponse(template.render(context, request))

def choose_company(request):
    template1 = loader.get_template('insurance_app/choose_company.html')
    company_user = CompanyUser.objects.filter(user=request.user)
    print(company_user)
    if company_user:
        context = {'company_user': company_user}
        return HttpResponse(template1.render(context, request))
    else:
        return render(request, 'insurance_app/choose_company_info.html')

def company_is_chosen(request, IM_NUMIDENT):
    template1 = loader.get_template('insurance_app/text_page.html')
    request.session['company_IM_NUMIDENT'] = IM_NUMIDENT
    company = Company.objects.filter(IM_NUMIDENT=IM_NUMIDENT).last()
    context = {'text': 'Ви увійшли у компанію '+ company.IAN_FULL_NAME}
    return HttpResponse(template1.render(context, request))

def company_logout(request, IM_NUMIDENT):
    template1 = loader.get_template('insurance_app/text_page.html')
    request.session['company_IM_NUMIDENT'] = None
    company = Company.objects.filter(IM_NUMIDENT=IM_NUMIDENT).last()
    context = {'text': 'Ви вийшли з компанії '+ company.IAN_FULL_NAME}
    return HttpResponse(template1.render(context, request))

def company_list(request):
    user = request.user
    try:
        user_companies = CompanyUser.objects.filter(user=user)
    except:
        user_companies = None
    try:
        company_docs = Documents.objects.filter(user=user, type_of_contract = 'contract')
    except:
        company_docs = None
    try:
        session_company = request.session['company_IM_NUMIDENT']
        print(session_company)
    except:
        session_company = None
    return render(request, 'insurance_app/company_list.html', {'user_companies': user_companies,
                                                               'session_company': session_company,
                                                               'company_docs': company_docs})

@csrf_exempt
def add_info_to_company(request, company_IM_NUMIDENT):
    db_obj = DatabaseAccess()
    user = request.user
    company_info = CompanyInfo.objects.get(IM_NUMIDENT = company_IM_NUMIDENT)
    address = request.POST['info_address']
    bank_props = request.POST['bank_props']
    position = request.POST['position']
    pib = request.POST['pib']
    action_base = request.POST['action_base']
    db_obj.insert_change_request(user, company_info, address, bank_props, position, pib, action_base)
    template1 = loader.get_template('insurance_app/text_page.html')
    context = {'text': 'Запит на зміну інформації про компанію ' + company_info.IAN_FULL_NAME + ' був відправлений адміністратору'}
    return HttpResponse(template1.render(context, request))

def company_detail(request, company_IM_NUMIDENT):
    last_date = Company.objects.last().update_date
    str_last_date = last_date.strftime("%d-%m-%Y %H:%M")
    user_flag = False
    user = request.user
    company_info = CompanyInfo.objects.get(IM_NUMIDENT = company_IM_NUMIDENT)
    form1 = AddInfoToCompany(instance=company_info)
    try:
        company = Company.objects.get(IM_NUMIDENT=company_IM_NUMIDENT, update_date=last_date)
        rows = CompanyUser.objects.filter(user=user)
        for row in rows:
            if row.company_info.IM_NUMIDENT == company.IM_NUMIDENT:
                user_flag = True
    except ObjectDoesNotExist:
        company = None
    return render(request, 'insurance_app/company_detail.html', {'company': company, 'user_flag': user_flag, 'str_last_date':str_last_date, 'form1':form1})

@csrf_exempt
def update_database(request):
    if request.is_ajax() and request.method == 'POST':
        alert_data = request.POST["alert_data"]
        if int(alert_data) > 7:
            processor = Processor()
            thread = threading.Thread(target=processor.update_company)
            thread.start()
            return JsonResponse({'context': 'База даних компаній буде оновлена'})
        elif alert_data.strip() == 'None':
            processor = Processor()
            thread = threading.Thread(target=processor.load_company)
            thread.start()
            return JsonResponse({'context': 'База даних компаній буде завантажена'})
        else:
            return JsonResponse({'context': 'База даних компаній НЕ буде оновлена'})

@csrf_exempt
def accept_chosen_request(request):
    request_id = request.POST.get('request_id')
    confirm_request = Request.objects.get(id = request_id)
    confirm_request.confirm=True
    confirm_request.save()
    return JsonResponse({})

@csrf_exempt
def accept_all_request(request):
    requests = Request.objects.all()
    for request in requests:
        if request.confirm == False:
            request.confirm=True
            request.save()
    return JsonResponse({})

@csrf_exempt
def load_to_database(request):
    db_obj = DatabaseAccess()
    db_obj.update_company_user()
    return JsonResponse({})

def check_requests():
    flag=True
    rows = Request.objects.all()
    for row in rows:
        if row.confirm==False:
            flag=False
            break
    return flag

def admin_page(request):
    user = request.user
    admin = user.is_superuser
    db_obj = DatabaseAccess()
    try:
        data = db_obj.get_update_data()
        now = timezone.now()
        alert_data = (now - data).days
    except:
        alert_data = None
    requests = Request.objects.all()
    template = loader.get_template('insurance_app/admin_page.html')
    check_requests_flag = check_requests()
    print(dir(requests))
    context = {
        'admin': admin,
        'requests': requests,
        'check_requests_flag' : check_requests_flag,
        'alert_data': alert_data,
    }
    return HttpResponse(template.render(context, request))

def admin_page_contract(request):
    user = request.user
    admin = user.is_superuser
    docs = Documents.objects.all()
    template = loader.get_template('insurance_app/admin_page_contract.html')
    context = {
        'admin': admin,
        'docs': docs,
    }
    return HttpResponse(template.render(context, request))

def received_contract_act(request, doc_id):
    user = request.user
    doc = Documents.objects.get(id=doc_id)
    if request.POST:
        file_location_received = request.POST['file_location_received']
        doc.file_location_received = file_location_received
        doc.received = True
        doc.signed_by_client = True
        doc.save()
        return redirect('insurance_app:admin_page_contract')
    else:
        doc_form = DocContractActForm()
        template = loader.get_template('insurance_app/received_contract_act.html')
        context = {
            'doc':doc,
            'user':user,
            'doc_form': doc_form,
        }
        return HttpResponse(template.render(context, request))

def received_bill(request, doc_id):
    user = request.user
    doc = Documents.objects.get(id=doc_id)
    if request.POST:
        file_location_received = request.POST['file_location_received']
        current_payment_amount = request.POST['current_payment_amount']
        doc.file_location_received = file_location_received
        doc.current_payment_amount = current_payment_amount
        doc.received = True
        doc.signed_by_client = True
        if float(current_payment_amount) >= doc.full_payment_amount:
            doc.paid_in_full = True
        doc.save()
        return redirect('insurance_app:admin_page_contract')
    else:
        doc_form = DocBillForm()
        template = loader.get_template('insurance_app/received_bill.html')
        context = {
            'doc':doc,
            'user':user,
            'doc_form': doc_form,
        }
        return HttpResponse(template.render(context, request))

def add_company(request):
    user = request.user
    template = loader.get_template('insurance_app/add_company.html')
    if request.method == "POST":
        pass
    else:
        form3 = AddCompanyForm()
        form4 = DeleteCompanyForm()
        form4.fields['company']._set_queryset(CompanyUser.objects.filter(user = user))
    context = {
        'user' : user,
        'form3': form3,
        'form4': form4,
    }
    return HttpResponse(template.render(context, request))

def user_page(request):
    user = request.user
    template = loader.get_template('insurance_app/user_page.html')
    if request.method == "POST":
        form1 = UserUpdateForm(request.POST,instance=user)
        form2 = UserProfileForm(request.POST,instance=user.userprofile)
        if form1.is_valid() and form2.is_valid():
            post1 = form1.save(commit=False)
            post2 = form2.save(commit=False)
            post1.save()
            post2.save()

insurance_app/templates/insurance_app/add_userprofile.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated and form != None %}
<div class="center-block">
    <div class="form-div">
        <h2>Додайте інформацію <br> в аккаунт (необов'язково)</h2>
    <form method="post" action="{% url 'insurance_app:add_userprofile' %}">
        {% csrf_token %}
        {{ form }}
        <div class="col-md-20 text-center">
            <button id='add' type="submit" class="btn btn-dark">Додати</button>
        </div>
    </form>
    </div>
</div>
<style>
@media screen and (orientation: portrait) {
    .center-block{
    width: 100vw;
    height: 70vh;
    display: flex;
    align-items: center;
    justify-content: center;
    }
    .form-div{
    width:90%
    }
    #add{
    margin-top: 5%
    }
}
@media screen and (orientation: landscape) {
    .center-block{
    display: block;
    margin: auto;
    width: 80%;
    margin-top: 5%;
    }
    #add{
    margin-top: 3%
    }
}
@media screen and (min-width: 1025px) {
    .center-block{
    display: block;
    margin: auto;
    width: 45%;
    margin-top: 7%;
    }
    #add{
    margin-top: 3%
    }
}
.center-block h2{
    text-align: center;
}
.errorlist {
    color: red
}
</style>
{% else %}
Ви не зареєстровані
{% endif %}
{% endblock content %}

insurance_app/templates/insurance_app/admin_page_contract.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if admin == True %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
<script>
function doIt() {
        console.log(document.getElementById('update_database').value);
       $.ajax({
         type: "POST",
         url: "update_database/",
         data: {
            alert_data: document.getElementById('update_database').value,
         },
         success: function(data) {
           alert(data.context);
         },
         error: function(xhr, textStatus, errorThrown) {
           alert("Error: "+errorThrown+xhr.status+xhr.responseText);
         }
       });
     }
$(document).ready(function () {
        $('[id^="confirm_request_"]').bind("click", function(){
            request_id = this.value;
            button_id = '#' + this.id;
            console.log(button_id);
            $.ajax({
                type:"POST",
                data: {'request_id':request_id},
                url: 'accept_chosen_request/',
                success: function(){
                $(button_id).removeClass('btn btn-dark').addClass('btn btn-success');
                $(button_id).text('Підтверджено');
                },
            });
        });
        $("#confirm_all").bind("click", function(){
            button_id = '#' + this.id;
            console.log(button_id);
            $.ajax({
                type:"POST",
                url: 'accept_all_request/',
                success: function(){
                $("#confirm_all").removeClass('btn btn-dark').addClass('btn btn-success');
                $("#confirm_all").text('Підтверджено все');
                },
            });
        });
        $("#load_to_database").bind("click", function(){
            button_id = '#' + this.id;
            console.log(button_id);
            $.ajax({
                type:"POST",
                url: 'load_to_database/',
                success: function(){
                $("#load_to_database").removeClass('btn btn-dark').addClass('btn btn-success');
                $("#load_to_database").text('Завантажено');
                },
            });
        });
    $('#table-id').DataTable( {
        "scrollX": true,
		"language": {
			"url": "https://cdn.datatables.net/plug-ins/1.10.21/i18n/Ukrainian.json",
		},
	} );
});
</script>
<div class="table-div">
<table id="table-id" class="display nowrap dataTable dtr-inline collapsed" data-page-length='10'>
    <thead>
        <tr>
            <th id="ID">ID</th>
            <th id="IAN_FULL_NAME">Найменування</th>
            <th id="IM_NUMIDENT">Код ЄДРПОУ</th>
            <th id="type_of_contract">Тип документу</th>
            <th id="file_location_sended">Розташування відправленого файлу</th>
            <th id="file_location_received">Розташування отриманого файлу</th>
            <th id="signed_by_us">Підписано нами</th>
            <th id="signed_by_client">Підписано отримувачем</th>
            <th id="full_payment_amount">Повна сума для оплати</th>
            <th id="current_payment_amount">Оплачено зараз</th>
            <th id="paid_in_full">Оплачено повністю</th>
            <th id="sended">Відправлено отримувачу</th>
            <th id="recived">Отримано адміном</th>
            <th id="CONFIRM_BUTTON">Кнопка підтвердження</th>
        </tr>
    </thead>
    <tbody>
        {% for doc in docs %}
            <tr>
                <td>{{ doc.id }}</td>
                <td>{{ doc.company_info.IAN_FULL_NAME }}</td>
                <td>{{ doc.company_info.IM_NUMIDENT }}</td>
                <td>{{ doc.type_of_contract }}</td>
                <td>{{ doc.file_location_sended }}</td>
                <td>{{ doc.file_location_received }}</td>
                <td>{{ doc.signed_by_us }}</td>
                <td>{{ doc.signed_by_client }}</td>
                <td>{{ doc.full_payment_amount }}</td>
                <td>{{ doc.current_payment_amount }}</td>
                <td>{{ doc.paid_in_full }}</td>
                <td>{{ doc.sended }}</td>
                <td>{{ doc.received }}</td>
                {% if doc.type_of_contract == 'contract' and doc.received == False %}
                <td><a href="{% url 'insurance_app:received_contract_act' doc.id %}"><button class="btn btn-dark">Отримано контракт</button></a></td>
                {% elif doc.type_of_contract == 'act' and doc.received == False %}
                <td><a href="{% url 'insurance_app:received_contract_act' doc.id %}"><button class="btn btn-dark">Отримано акт</button></a></td>
                {% elif doc.type_of_contract == 'bill' and doc.paid_in_full == False %}
                <td><a href="{% url 'insurance_app:received_bill' doc.id %}"><button class="btn btn-dark">Отримано рахунок</button></a></td>
                {% else %}
                <td> ----- </td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
    </table>
</div>

<style>
@media screen and (orientation: portrait) {
    .table-div{
    margin-left:1%;
    margin-top:2%;
    }
    .load-div{
    margin-top:15%;
    margin-left:1%;
    }
    .update-div{
    margin-top:2%;
    margin-left:1%;
    }

}
@media screen and (orientation: landscape) {
    .table-div{
    margin-top:2%;
    }
    .load-div{
    margin-top:2%;
    margin-left:1%;
    }
    .update-div{
    margin-top:2%;
    margin-left:1%;
    }

}
@media screen and (min-width: 1025px) {
    .table-div{
    margin-left: 0.1%;
    margin-top:2%;
    }
    .load-div{
    margin-left: 1%;
    margin-top:2%;
    }
    .update-div{
    margin-top:0.5%;
    margin-left:1%;
    }
}
#table-id{
    width:99%
}
.confirm-div{
    margin-top:2%;
    position:absolute;
    right:1%
}
.alert-p{
    color:red
}
</style>
{% else %}
Ви не зареєстровані або не увійшли в аккаунт
{% endif %}
{% endblock content %}

insurance_app/templates/insurance_app/create_contract.html
{% extends "base.html" %}
{% block content %}
    <div class="col-12 text-center py-5">
            <h4 class='my-5 py-5'>Для роботи потрібно укласти договір з
            компанією "Страхова компанія "МИР"</h4>
            <h5>Договір для компанії {{company_info.IAN_FULL_NAME}}</h5>
            <p>Ви можете укласти договір зараз, або пропустити і укласти його пізніше.
            Для того щоб пропустити цей крок, натисніть "Пропустити"</p>
        <form method="post" action="{% url 'insurance_app:create_contract' IM_NUMIDENT %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-dark">Укласти договір</button>
            <a href="{% url 'insurance_app:add_company' %}">Пропустити</a>
        </form>
      </div>
{% endblock %}

insurance_app/templates/insurance_app/csrf_failure.html
{% extends 'base.html' %}
{% block content %}
{{ message }}
{% endblock %}

insurance_app/templates/insurance_app/login_user.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not user.is_authenticated %}
<div class="center-block">
    <div class="form-div">
        <h2>Вхід</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="col-md-20 text-center">
            <button id ='enter' type="submit" class="btn btn-dark">Увійти</button>
            <a href="{% url 'insurance_app:password_reset' %}">
                <button id='forgot-password' type="button" class="btn btn-dark"> Забув пароль</button>
            </a>
        </div>
    </form>
        </div>
</div>
<style>
@media screen and (orientation: portrait) {
    .center-block{
    width: 100vw;
    height: 70vh;
    display: flex;
    align-items: center;
    justify-content: center;
    }
    .form-div{
    width:90%
    }
}
@media screen and (orientation: landscape) {
    .center-block{
    display: block;
    margin: auto;
    width: 80%;
    margin-top: 5%;
    }
}
@media screen and (min-width: 1025px) {
    .center-block{
    display: block;
    margin: auto;
    width: 45%;
    margin-top: 9%;
    }
}
.center-block h2{
    text-align: center;
}
.errorlist {
    color: red
}
</style>
{% else %}
Ви вже увійшли в аккаунт
{% endif %}
{% endblock %}

insurance_app/templates/insurance_app/order.html
{% extends 'base.html' %}
{% block content %}
{% if session_company %}
{% if order != None %}
<div id="order_session_company">
    <h4>Замовлення буде зроблене для компанії: <br>{{session_company.IAN_FULL_NAME}}</h4>
</div>
<div class="center-block">
    <div class="one">
        {% if user_orders_offered and user_orders %}
        <p class="text-secondary">Ви можете замовити:</p>
        {% if user_orders_offered3 %}
        {% for order in user_orders_offered3 %}
        <div class="one-text">
            <a href="{% url 'insurance_app:reject_order' order.id %}"><img id='reject' src="/static/media/dis.png" title="Видалити"></a>
            Компанія: {{order.company_info.IAN_FULL_NAME}}<br>
                Звітня дата: {{order.reporting_date}}<br>
                Вид розрахунку: {{order.calc_type}}
            <a href="{% url 'insurance_app:order' order.id %}">
                <p id="load_order">Завантажити в розрахунки</p>
            </a>
        </div>
        {% endfor %}
        <a href="{% url 'insurance_app:order_offered' %}">Дивитися всі пропозиції</a>
        {% else %}
        {% for order in user_orders_offered %}
        <div class="one-text">
            <a href="{% url 'insurance_app:reject_order' order.id %}"><img id='reject' src="/static/media/dis.png" title="Видалити"></a>
            Компанія: {{order.company_info.IAN_FULL_NAME}}<br>
                Звітня дата: {{order.reporting_date}}<br>
                Вид розрахунку: {{order.calc_type}}
            <a href="{% url 'insurance_app:order' order.id %}">
                <p id="load_order">Завантажити в розрахунки</p>
            </a>
        </div>
        {% endfor %}
        {% endif %}
        {% endif %}
    </div>
    <div class="two form-div">
    <h4>Зробити замовлення</h4>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="col-md-20 text-center">
            <button id ='enter' type="submit" class="btn btn-dark">Замовити</button>
        </div>
    </form>
    </div>
    <div class="three">
        <a href="{% url 'insurance_app:order_history'%}">
        <h5 class="text-info">Історія замовлень</h5>
        </a>
    </div>
</div>
{% else %}
<div class="col-12 text-center py-5">
            <h5>Ви не маєте такого замовлення або це замовлення не для цієї компанії</h5>
      </div>
{% endif %}
{% else %}
<div class="col-12 text-center py-5">
            <h5>Ви не обрали компанію для того, щоб здійснити замовлення. <br>Будь ласка зайдіть у вкладку
            "Компанія" -> "Змінити компанію" на навігаційній панелі та оберіть її. <br>Якщо ж у цій вкладці немає компаній, то:<br>
                1) Натисніть на вкладку "Компанія" на навігаційній панелі та оберіть вкладку "Додати/видалити компанію".<br>
                У пункті "Вкажіть компанію, яку ви хочете додати:" оберіть потрібну Вам компанію.<br>
                2) Якщо ви вже додали компанію, то вона зявиться у вкладці "Змінити компанію",<br>
                коли адміністратор сайту підтвердить її.</h5>
      </div>
{% endif %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2({width: '100%'});
});
</script>
<style>
@media screen and (orientation: portrait) {
    .center-block{
    width: 100vw;
    height: 70vh;
    display: flex;
    align-items: center;
    justify-content: center;
    }
    .form-div{
    width:90%
    }
}
@media screen and (orientation: landscape) {
    .center-block{
    display: block;
    margin: auto;
    width: 80%;
    margin-top: 5%;
    }
}
@media screen and (min-width: 1025px) {
    .center-block{
    display:flex;
    margin: auto;
    width: 100%;
    margin-top: 4%;
    }
    .two h4{text-align:center}
    .two{width:46%;margin:20px}
    .one,.three{width:22%;margin:40px}
}
}
.center-block h2{
    text-align: center;
}
.one .one-text {font-size:16px;text-align:left}
.one .text-secondary {font-size:20px;text-align:center}
.three h5 {font-size:20px;text-align:center}

.errorlist {
    color: red
}
.select2-container .select2-selection--single {
    height: 37px;
    border: 1px solid #d5d7db;
}
#load_order{
    font-size: 12pt;
    text-align:right;
}
#reject{
 height:20px
 }
#img-show{
 height:7px;
 margin-left:2px;
 }
#order-error {
 color:red
 }
#order_session_company{
    margin-top:35px;
    text-align:center;
}
.text-danger{
    font-size:14pt;
}
.text-success{
    font-size:14pt;
}
</style>
{% endblock content %}

insurance_app/templates/insurance_app/show_count_error.html
{% extends "base.html" %}
{% block content %}
    <div class="col-12 text-center py-5">
        <h5>{{error}}</h5>
      </div>
{% endblock %}