insurance/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('insurance_app/', include('insurance_app.urls')),
    # url('django-webix/', include('django_webix.urls')),
]

insurance_app/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .forms import MyPasswordResetForm, MyPasswordChangeForm, MyAuthenticationForm
app_name='insurance_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('admin_page', views.admin_page, name='admin_page'),
    path('admin_page_contract', views.admin_page_contract, name='admin_page_contract'),
    path('login_user', auth_views.LoginView.as_view(template_name ='insurance_app/login_user.html', form_class = MyAuthenticationForm), name='login_user'),
    path('choose_company',views.choose_company, name='choose_company'),
    path('password/reset/', auth_views.PasswordResetView.as_view(template_name ='insurance_app/password_reset_form.html', form_class = MyPasswordResetForm,
    email_template_name = 'insurance_app/password_reset_email.html', success_url = reverse_lazy('insurance_app:password_reset_done')), name='password_reset'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name ='insurance_app/password_reset_done.html'), name='password_reset_done'),
    path('password/reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(form_class = MyPasswordChangeForm, success_url = reverse_lazy('insurance_app:password_reset_complete'),template_name ='insurance_app/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password/reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name ='insurance_app/password_reset_complete.html'),
        name='password_reset_complete'),
    path('password/change/', auth_views.PasswordChangeView.as_view(template_name ='insurance_app/password_change_form.html',
                                                                   form_class = MyPasswordChangeForm,success_url = reverse_lazy('insurance_app:password_change_done') ), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(template_name ='insurance_app/password_change_done.html'), name='password_change_done'),
    path('add_userprofile',views.add_userprofile,name='add_userprofile'),
    path('logout', views.logout, name='logout'),
    path('register',views.register,name='register'),
    path('add_company', views.add_company, name='add_company'),
    path('accept_chosen_request/',views.accept_chosen_request, name='accept_chosen_request'),
    path('accept_all_request/',views.accept_all_request, name='accept_all_request'),
    path('load_to_database/',views.load_to_database, name='load_to_database'),
    path('add_chosen_company/',views.add_chosen_company,name='add_chosen_company'),
    path('delete_chosen_company/',views.delete_chosen_company,name='delete_chosen_company'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('update_database/',views.update_database, name='update_database'),
    path('auto_insurance', views.auto_insurance, name='auto_insurance'),
    path('auto_fill/',views.auto_fill, name='auto_fill'),
    path('company_list',views.company_list, name='company_list'),
    path('company_detail/<str:company_IM_NUMIDENT>',views.company_detail, name='company_detail'),
    path('add_info_to_company/<str:company_IM_NUMIDENT>',views.add_info_to_company, name='add_info_to_company'),
    path('order/<int:order_id>',views.order, name='order'),
    path('order_history',views.order_history, name='order_history'),
    path('reject_order/<int:order_id>',views.reject_order, name='reject_order'),
    path('order_offered',views.order_offered, name='order_offered'),
    path('company_is_chosen/<str:IM_NUMIDENT>',views.company_is_chosen, name='company_is_chosen'),
    path('create_contract/<str:IM_NUMIDENT>',views.create_contract, name='create_contract'),
    path('show_count_result/<int:order_id>',views.show_count_result, name='show_count_result'),
    path('show_count_error/<int:order_id>/<str:reason>',views.show_count_error, name='show_count_error'),
    path('show_order/<int:order_id>',views.show_order, name='show_order'),
    path('documents/<str:IM_NUMIDENT>',views.documents, name='documents'),
    path('received_contract_act/<int:doc_id>', views.received_contract_act, name='received_contract_act'),
    path('received_bill/<int:doc_id>', views.received_bill, name='received_bill'),
    path('try', views.tryx, name='try'),
    path('user_page', views.user_page, name='user_page'),
    path('company_logout/<str:IM_NUMIDENT>', views.company_logout, name='company_logout'),
]

insurance/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>InsuranceSite</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="/static/css/style_base.css" type="text/css"/>
  <link  rel="shortcut icon" type="image/png" href="/static/media/favicon.ico"/>
</head>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'insurance_app:index' %}" >Страхування</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'insurance_app:index' %}">Головна</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'insurance_app:auto_insurance' %}">Автоцивілка</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item" style="display: inline-block">
        <div class="btn-group" style="display: inline-block">
        <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Компанія</button>
        <div class="dropdown-menu dropdown-menu-left">
        {% if request.session.company_IM_NUMIDENT %}
          <a class="dropdown-item" href="{% url 'insurance_app:company_detail' request.session.company_IM_NUMIDENT %}">Детальніше про компанію</a>
          <a class="dropdown-item" href="{% url 'insurance_app:documents' request.session.company_IM_NUMIDENT %}">Документи</a>
          <a class="dropdown-item" href="#">Завантаження</a>
          <a class="dropdown-item" href="{% url 'insurance_app:order' 0 %}">Замовити розрахунок</a>
          <a class="dropdown-item" href="{% url 'insurance_app:company_logout' request.session.company_IM_NUMIDENT %}">Вийти</a>
        {% else %}
          <a class="dropdown-item" href="{% url 'insurance_app:add_company' %}">Додати/видалити компанію</a>
          <a class="dropdown-item" href="{% url 'insurance_app:company_list' %}">Увійти</a>
        {% endif %}
        </div>
      </div>
      </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav">
    {% if user.is_authenticated %}
    <li class="nav-item">
      <div class="btn-group" style="display: inline-block">
        <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</button>
        <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item" href="{% url 'insurance_app:user_page' %}">Аккаунт</a>
        <a class="dropdown-item" href="{% url 'insurance_app:password_change' %}">Змінити пароль</a>
        {% if user.is_superuser %}
          <a class="dropdown-item" href="{% url 'insurance_app:admin_page' %}">Компанії (адмін) </a>
          <a class="dropdown-item" href="{% url 'insurance_app:admin_page_contract' %}">Договори (адмін) </a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'insurance_app:logout' %}">Вийти</a>
        </div>
      </div>
    </li>
    {% else %}
      <li class="nav-item"><a class="nav-link" href="{% url 'insurance_app:login_user' %}">Увійти</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'insurance_app:register' %}">Реєстрація</a></li>
    {% endif %}
  </ul>

  </div>

</nav>
<body>
    <div class="container-div">
          {% block content %}
          {% endblock content %}
          {% block login %}
          {% endblock login %}
    </div>
    <footer class="footer">
      <div class="footer-text">Страхування</div>
    </footer>

</body>
</html>